
/*CREATE THE DATABASE*/
USE [master]
CREATE DATABASE BlazorAppDb
GO

/*USE THE DATABASE*/
USE [BlazorAppDb]
GO

/*CREATE TABLE*/

CREATE TABLE Items (
    Id INT PRIMARY KEY IDENTITY,
    Name NVARCHAR(100) NOT NULL,
    Description NVARCHAR(255) NOT NULL,
    Price DECIMAL(18, 2) NOT NULL,
    CreatedAd NVARCHAR(20) NOT NULL,
	IsDeleted BIT NOT NULL DEFAULT 0,
);

GO